services:
  postgres:
    image: postgres:16-alpine
    container_name: documentai-db
    environment:
      POSTGRES_DB: documentai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Munk123
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: documentai-ollama
    ports:
      - "11434:11434"